plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.107'
}

group = 'io.github.milkycloud-dev'
version = '0.1.0'

base {
    archivesName = 'eturlia-compat-sable'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = '21.1.249'
}

repositories {
    mavenCentral()
    exclusiveContent {
        forRepository { maven { url = 'https://api.modrinth.com/maven' } }
        filter { includeGroup 'maven.modrinth' }
    }
}

dependencies {

}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}
